### ISSUE TITLE
Selection in WildMenu in Vim invisible

### ISSUE THREAD

**Issue by evtuhovich** [altercation/vim-colors-solarized#10]
Here is a patch

<pre>diff --git a/colors/solarized.vim b/colors/solarized.vim
index 81c2c99..a97b6c7 100644
--- a/colors/solarized.vim
+++ b/colors/solarized.vim
@@ -670,7 +670,7 @@ exe "hi Title"          . s:fg_orange .s:bg_none   .s:fmt_bold
 exe "hi Visual"         . s:fg_none   .s:bg_base02 .s:fmt_stnd
 exe "hi VisualNOS"      . s:fg_none   .s:bg_base02 .s:fmt_stnd
 exe "hi WarningMsg"     . s:fg_red    .s:bg_none   .s:fmt_bold
-exe "hi WildMenu"       . s:fg_base1  .s:bg_base02 .s:fmt_none
+exe "hi WildMenu"       . s:fg_base1  .s:bg_base01 .s:fmt_none
 exe "hi Folded"         . s:fg_base0  .s:bg_base02 .s:fmt_undr   .s:sp_base03
 exe "hi FoldColumn"     . s:fg_base0  .s:bg_base02 .s:fmt_bold
 exe "hi DiffAdd"        . s:fg_green  .s:bg_none   .s:fmt_revr
</pre>

In light version if you type :help a&lt;Tab>&lt;Left> you will see wildmenu, where selected element is invisible

**Comment by altercation** [comment]
On it. Will post here after addressed.

**Comment by altercation** [comment]
Merging this into the global project issue here:
https://github.com/altercation/solarized/issues/45

**Comment by altercation** [comment]
I've updated the colors in https://github.com/altercation/solarized/commit/177c82b1636b864c92937c9780658cc6eca87aa4 and will follow up this issue in the main repository (link above).

**Comment by evtuhovich** [comment]
Thanx you
