### ISSUE TITLE
Command-line vim exits with code 1 on Mac OS X

### ISSUE THREAD

**Issue by thelibrarian** [altercation/vim-colors-solarized#12]
With the solarized theme installed (Pathogen style), the built-in command line Vim on Mac OS 10.6 exits with code 1, even though I am not using this theme on the command-line, only in the GUI. The mere presence of this theme causes this error (i.e. removing its directory from `~/.vim/bundle` stops the problem).

The version output is as follows:

<pre><code>VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Feb 11 2010 14:27:45)
Included patches: 1-108
Compiled by stripes@il0204d-dhcp43.apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+cryptv +cscope +cursorshape +dialog_con +diff +digraphs -dnd -ebcdic 
-emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path +find_in_path 
+float +folding -footer +fork() -gettext -hangul_input +iconv +insert_expand 
+jumplist -keymap -langmap +libcall +linebreak +lispindent +listcmds +localmap 
+menu +mksession +modify_fname +mouse -mouseshape -mouse_dec -mouse_gpm 
-mouse_jsbterm -mouse_netterm -mouse_sysmouse +mouse_xterm +multi_byte 
+multi_lang -mzscheme -netbeans_intg -osfiletype +path_extra -perl +postscript 
+printer -profile -python +quickfix +reltime -rightleft -ruby +scrollbind 
-signs +smartindent -sniff +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H     -arch armv7 -arch i386 -arch x86_64 -g -Os -pipe -mdynamic-no-pic        
Linking: gcc   -arch armv7 -arch i386 -arch x86_64             -o vim       -lm  -lncurses
</code></pre>

**Comment by altercation** [comment]
It can run in 7.2 in some cases but I have 7.3 as the minimum required version (this is only listed on the vim.org script page however... I should put it in the main README).

I've spent a couple days refactoring and changing the way some code gets loaded and defined. I'd give the currently available version a whirl on 7.2. Let me know.

**Comment by thelibrarian** [comment]
This error was occurring with cf4aee2f5f19a3f0ea30, but not with a211ae8fc9d36d06c771. I've now pulled down 9f2b8bc69ddd589156d9 on my home computer (different computer, same OS as my work computer), and it seems to not be returning 1 on exit anymore.

I should note that this problem was not causing Vim to malfunction at all - everything worked fine (opening, editing saving etc.) it would just return 1 on exit, which was causing problems with Git.

I will now close this issue, as one of your latest edits seems to have stopped the problem.

**Comment by altercation** [comment]
Thanks. If I had more time I'd try to figure out what was going on specifically. I suspect it was the multiple gui/cterm definitions.
