### ISSUE TITLE
Most colors grayed out on iterm2

### ISSUE THREAD

**Issue by alfredodeza** [altercation/vim-colors-solarized#13]
For the dark palette on iterm2 the `bright` column has most colors grayed out. 

I am not sure if that is the actual intention, but it creates issues for sure because most 
terminal applications tend to sue the ANSI colors from the `bright` column.

If this is intentional, may I suggest moving away from grey-like colors?

**Comment by altercation** [comment]
Please see https://github.com/altercation/solarized/issues#issue/8
