### ISSUE TITLE
MacVim background is always white no matter which bg

### ISSUE THREAD

**Issue by giantrobotbee** [altercation/vim-colors-solarized#14]
I was setting up a brand new computer with all my settings. I have solarized working on my laptop and love it, so I copied over everything from my laptop, but my MacVim always has a white background. The line numbers and fonts are colored properly, and I can tell that some part of the theme is taking hold because I can toggle the dark/light with F5, but I can't seem to get rid of the white.

**Comment by altercation** [comment]
Merged with https://github.com/altercation/vim-colors-solarized/issues/#issue/9
