### ISSUE TITLE
Weird vim-solarized window on my ubuntu is there a way to change the background to default ?

### ISSUE THREAD

**Issue by himanshuxd** [altercation/vim-colors-solarized#164]
Vim appears with a grey background, black background on text with pale text.

**Comment by glrodasz** [comment]
I had the same problem and this fixed it: https://github.com/altercation/vim-colors-solarized#important-note-for-terminal-users

**Comment by himanshuxd** [comment]
Thanks @garethderioth had found a solution too:

`hi Normal ctermbg=none`

**Comment by vitchyr** [comment]
@himanshuxd This fixed the coloring for my file text, but the line numbers are still colored weirdly. Is there something to fix that? Also, how did you figure that command out?

edit: `hi LineNr ctermbg=none` did it, but I'm still not sure why this was necessary in the first place.

**Comment by himanshuxd** [comment]
@vitchyr sometimes the problem is the terminal font, for me changing to Sans Roboto Mono fixed the line number and other rendering issues, this is a great writeup that informs on color customization of vim I used it to figure that change out: https://alvinalexander.com/linux/vi-vim-editor-color-scheme-syntax cya.
