### ISSUE TITLE
Dark Color scheme not getting activated

### ISSUE THREAD

**Issue by luckydev** [altercation/vim-colors-solarized#17]
I moved solarized.vim to ./vim/colors/ directory.

set these lines in my gvimrc

syntax enable
set background=dark
colorscheme solarized

and I get just the light background. not the dark one. how can i get it. is this an issue with solarized?

**Comment by andrusha** [comment]
You should have moved it to `~/.vim/colors`, not `./vim/colors` directory

**Comment by altercation** [comment]
@luckydev, are you still experiencing this issue? I've added a new Solarized gui menu in the currently available code on github and you can live toggle the dark background mode from there as an easy test.

**Comment by luckydev** [comment]
nope. im not experiencing this. had to restart macvim to get this in effect. otherwise no probs
