### ISSUE TITLE
Colors aren't quite right in Neovim

### ISSUE THREAD

**Issue by jc00ke** [altercation/vim-colors-solarized#179]
I'm using Alacritty, and after changing the bg color for it the light bg color matches up well:

![0_selection_002](https://cloud.githubusercontent.com/assets/18191/23826252/9fab99e8-064d-11e7-869a-be4ffec59891.png)

But inside neovim, using the latest from this project, the bg colors don't line up

![0_selection_001](https://cloud.githubusercontent.com/assets/18191/23826257/ba565094-064d-11e7-9b96-bf1539ed6159.png)

Config at the bottom of my `init.vim` file looks correct. Am I missing something?

**Comment by kreedz** [comment]
May be this will help you https://github.com/frankier/neovim-colors-solarized-truecolor-only
But I have not tried it myself.

**Comment by jc00ke** [comment]
That does look better, thanks @kreedz.
