### ISSUE TITLE
Some Color are too dark to identify

### ISSUE THREAD

**Issue by Clcanny** [altercation/vim-colors-solarized#186]
I'm using vim8 + iTerm2

some words and sentences are too dark for me, such as "let g:ycm_always_populate_location_list = 1" in my .vimrc, the whole .vimrc is in https://gist.github.com/Clcanny/df37a3141df7cd6fcfa68c2842cfb600.

Is there a way to substitute that color? Thx.

**Comment by Clcanny** [comment]
Soory, I found that someone have questioned about that.

The solution is to set "Minimum contrast" more high.

**Comment by LindyBalboa** [comment]
Might be worthwhile to link the solution.

**Comment by Clcanny** [comment]
In the newest version iTerm2, iTerm2 -> Perferences -> Appearance -> Theme -> Dark (High Constract), maybe work.
It's a long time, i forget the link, sorry.

**Comment by Clcanny** [comment]
my vim settings is as follow:
```shell
se t_Co=16
let g:solarized_termcolors=256
syntax enable
set background=dark
colorscheme solarized
```
may be work.
