### ISSUE TITLE
Bad spell words not visible anymore

### ISSUE THREAD

**Issue by erikw** [altercation/vim-colors-solarized#195]
Hello,

I've had the same vim configuration in regards to using solarized colorscheme and how my spelling is configured, for years and years. But today, possibly when I updated to vim-runtime 8.0.1389-1 in Arch, misspelled words stopped being underlined in terminal vim.

This is how it currenlty looks, bad word is not highlighted as it should:

![screenshot_2017-12-15-224931_260x145](https://user-images.githubusercontent.com/175286/34061952-8ac55c0c-e1ea-11e7-823a-89fae5be4b7b.png)

The spelling works in gvim+solarized and in terminal with other colorschemes.

I noticed that in the terminal SpellBad is set to

```vim
:hi SpellBad
SpellBad       xxx term=undercurl cterm=undercurl gui=undercurl guisp=Red
```

and I see from

```vim
:h undercurl
undercurl       not always available
```

So when I change vim-colors-solarized to user underline for terminal always instead of `undercurl`, this patch,

```patch
diff --git a/colors/solarized.vim b/colors/solarized.vim
index 70f5223..57f7372 100644
--- a/colors/solarized.vim
+++ b/colors/solarized.vim
@@ -360,7 +360,7 @@ endif
     let s:none            = "NONE"
     let s:t_none          = "NONE"
     let s:n               = "NONE"
-    let s:c               = ",undercurl"
+    let s:c               = ",underline"
     let s:r               = ",reverse"
     let s:s               = ",standout"
     let s:ou              = ""
```

and now the misspelled word are underlined as they have been for years for me!

![screenshot_2017-12-15-224953_282x140](https://user-images.githubusercontent.com/175286/34061956-91b56520-e1ea-11e7-8425-fad928b30d6c.png)

What could be the cause of this? Is there any reason for having `undercurl` set instead of `underline` for terminals? For GUI it makes sense to have the fancier undercurl of course, but not for terminal.

If not, I suggest my patch above =).

**Comment by luketurcotte** [comment]
Thanks for the suggested patch! I ran into this issue as well.

**Comment by KenKundert** [comment]
The suggested patch changes the way spelling errors are highlighted in gvim as well. You can leave gvim unchanged while fixing vim using:
```vim
if (has("gui_running"))
    let s:c = ",undercurl"                                     
else                                                                         
    let s:c = ",underline"                                     
endif
```
This should not be necessary. `:help undercurl` clearly says that when undercurl is not available underline will be used, but this must be broken in this release of vim.

**Comment by jflorian** [comment]
https://github.com/vim/vim/issues/2424 looks relevant.

**Comment by joshklod** [comment]
@jflorian 

> [vim/vim#2424](https://github.com/vim/vim/issues/2424) looks relevant.

Indeed, this issue is due to that bug. Solarized is not the problem, as @KenKundert pointed out.

@erikw 

I'm guessing this has been fixed by now, in which case this issue can be closed.  If not, try adding `set t_Cs=` to your vimrc.  That workaround is sufficient in some versions of Vim.

**Comment by erikw** [comment]
@joshklod I can confirm that it works now in vim `8.1.0374`! I'm closing the ticket.
