### ISSUE TITLE
Cursor in visual select mode is invisible

### ISSUE THREAD

**Issue by jtaby** [altercation/vim-colors-solarized#2]
on MacVim.app, if I enter visual mode, the cursor changes colors and becomes invisible.

**Comment by nickknw** [comment]
I see this too, sort of. For me it is not quite invisible, but close enough that it can be confusing. A shade that is a bit darker (for bg=light) or lighter (for bg=dark) would be easier to see.

**Comment by altercation** [comment]
I've simply locked the cursor to a specific bg/fg combination for now. Available as of now. It has a minor impact on this issue. I'm leaving this issue open as I may revert to non reverse visual mode highlighting. I like it but it proves problematic will have to use a static highlight.

**Comment by nickknw** [comment]
I noticed a bit of a difference, but it can still be pretty hard to see in some cases, here is an example:

http://i.imgur.com/kjoP1.png

In this screenshot, the 'e' is also selected, even though it doesn't appear to be at first glance.

**Comment by altercation** [comment]
New commit changes the visual selection color (different in vim / high color terminals / low color terminals ... readable here in all tests but feedback please). Pull or clone current repo and try.

**Comment by nickknw** [comment]
Looks great, thanks Ethan!

**Comment by drwebb** [comment]
I have a similar problem, but rather my cursor turns invisible when it is on a part of text that has been matched by a search.

I am using the dark background in vim, running vim in urxvt. When I use gvim the problem goes away, and it similarly works as expected when I use the light background in vim.
