### ISSUE TITLE
How to use with vim8 packages?

### ISSUE THREAD

**Issue by coolaj86** [altercation/vim-colors-solarized#213]
I've always used pathogen, but now that vim supports native plugins, I thought I'd give that a go:

```bash
mkdir -p ~/.vim/pack/plugins/start/

git clone --depth=1 \
  https://github.com/altercation/vim-colors-solarized.git \
  ~/.vim/pack/plugins/start/vim-colors-solarized
```

Not too surprised that it didn't work. I'm not sure what makes one package manager work vs another and if there needs to be a special file that isn't included in the repo currently.

Any thoughts?

**Comment by rharish101** [comment]
You need to set the color scheme after loading the packages. For example, this is my setup with solarized-dark:
```
packloadall          " load all plugins
silent! helptags ALL " load all helptags

" Syntax highlighting requires a loaded plugin
syntax on
set background=dark
let g:solarized_underline = 0 " disable underlining, esp. for folds
colorscheme solarized
```

Notice that the line `colorscheme solarized` is set **after** the line `packloadall`.

**Comment by coolaj86** [comment]
It works!

Thanks!
