### ISSUE TITLE
background is gray

### ISSUE THREAD

**Issue by muse117** [altercation/vim-colors-solarized#218]
The background colors is not normal. It is gray. I use ubuntu20.04. 
.vimrc config is:
syntax enable
set background=dark
colorscheme solarized
let g:solarized_termcolors=256

![Screenshot from 2020-06-29 16-06-48](https://user-images.githubusercontent.com/9733486/85989293-e8772c00-ba22-11ea-8a2f-12dfc8d5c676.png)

**Comment by fengwang** [comment]
Same problem here, as of vim 8.2.0814@archlinux.
But getting back to normal if turn off terminal transparency.

**Comment by TadeuOliveira** [comment]
I have a similar problem as @muse117 : if I don't include the `let g:solarized_termcolors=256` line to my _.vimrc_, my colorscheme is just the same as his. When I do so, I get a colorscheme that definitely isn't solarized
![image](https://user-images.githubusercontent.com/12589387/86919021-ecc7d700-c0fd-11ea-8eb6-d2139bbeb97c.png)

**Comment by sairuk** [comment]
call let before the colorscheme option and the scheme should have the full palette available when it loads.

e.g.
```
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
```

**Comment by TadeuOliveira** [comment]
I'm afraid that was not the problem. I've switched order of these three and still got the same result
By the way, I'm using ubuntu 20.04 as well
![image](https://user-images.githubusercontent.com/12589387/87295116-18bad200-c4db-11ea-92d0-9d7924e766d7.png)

**Comment by muse117** [comment]
> I'm afraid that was not the problem. I've switched order of these three and still got the same result
> By the way, I'm using ubuntu 20.04 as well
> ![image](https://user-images.githubusercontent.com/12589387/87295116-18bad200-c4db-11ea-92d0-9d7924e766d7.png)

This problem maybe a color support error in the terminal. You can also change the theme of the terminal to solarized. This problem will be fixed! https://github.com/aruhier/gnome-terminal-colors-solarized

**Comment by bam80** [comment]
Have you tried https://github.com/lifepillar/vim-solarized8?

**Comment by mariaortiz0401** [comment]
> Have you tried https://github.com/lifepillar/vim-solarized8?

Worked like a charm for me on Ubuntu 20.04 terminal

**Comment by TadeuOliveira** [comment]
> Have you tried https://github.com/lifepillar/vim-solarized8?

seems to be working, except for the background. 

![image](https://user-images.githubusercontent.com/12589387/87792831-cc44fe80-c81a-11ea-8d8b-f1b172048369.png)

**Comment by muse117** [comment]
> call let before the colorscheme option and the scheme should have the full palette available when it loads.
> 
> e.g.
> 
> ```
> set background=dark
> let g:solarized_termcolors=256
> colorscheme solarized
> ```

great! the question is solved
![Screenshot from 2020-07-18 10-31-43](https://user-images.githubusercontent.com/9733486/87842802-f1507480-c8e1-11ea-897f-9e49e3245888.png)

**Comment by muse117** [comment]
> I'm afraid that was not the problem. I've switched order of these three and still got the same result
> By the way, I'm using ubuntu 20.04 as well
> ![image](https://user-images.githubusercontent.com/12589387/87295116-18bad200-c4db-11ea-92d0-9d7924e766d7.png)

you try to add "let g:solarized_termtrans=1".

**Comment by muse117** [comment]
> I'm afraid that was not the problem. I've switched order of these three and still got the same result
> By the way, I'm using ubuntu 20.04 as well
> ![image](https://user-images.githubusercontent.com/12589387/87295116-18bad200-c4db-11ea-92d0-9d7924e766d7.png)

you try to add "let g:solarized_termtrans=1".
