### ISSUE TITLE
Sass and Less highlighting

### ISSUE THREAD

**Issue by necolas** [altercation/vim-colors-solarized#31]
Is there a way to include Sass and Less syntax highlighting? Thanks for all your work on this project.

**Comment by thelibrarian** [comment]
Language support is not the responsibility of the colour scheme. You need to install a syntax plugin to support Sass and Less. I suggest this one: https://github.com/tpope/vim-haml (it supports Haml, Sass and SCSS).

**Comment by necolas** [comment]
Thanks
