### ISSUE TITLE
Colors not behaving as expected

### ISSUE THREAD

**Issue by naftulikay** [altercation/vim-colors-solarized#34]
I'm having a pretty weird issue with trying to install vim-colors-solarized. I was able to install it and get it working, but this is what vim now looks like:

![Imagh](http://i.stack.imgur.com/yP0qL.png)

What am I doing wrong? Is this how it should look?

**Comment by stungeye** [comment]
Is this happening when trying to use vim via a terminal app? If so you should follow the instructions in the readme labelled "IMPORTANT NOTE FOR TERMINAL USERS".

A quick fix add the following line to your .vimrc before "colorscheme solarized":

let g:solarized_termcolors=256

**Comment by naftulikay** [comment]
It certainly looks better now, but is this right?

![helloworld](http://i.imgur.com/kwcKn.png)

**Comment by stungeye** [comment]
The line I gave you turns on 256 colour compatibility mode. So you are seeing the "the degraded 256 colorscheme".

If you want the full experience you'll have to follow the other instructions I pointed out.

**Comment by naftulikay** [comment]
I just used the Gnome Terminal extension to try and set my colors, and it didn't actually fix things. My terminal looks like this:

![one](http://i.imgur.com/dx2iz.png)

and VIM looks like this:

![two](http://i.imgur.com/gglCd.png)

**Comment by stungeye** [comment]
Now that you've solarized your terminal you can remove the "let g:solarized_termcolors=256" from your .vimrc file.
