### ISSUE TITLE
vim solarized background and text fail

### ISSUE THREAD

**Issue by huxley-sparks** [altercation/vim-colors-solarized#36]
![vim error](http://i.imgur.com/CtSsb.png)

I tried doing the standard options

> syntax enable
> set background=dark
> let g:solarized_termcolors=256

and even commenting out 

> term=builtin_ansi

but nothing has worked. I'm using spf13-vim,  solarized located at .vim/bundle/vim-color-solarized/color/.
I even tried a simple .vimrc with only those standard options in it but I get the same result.

**Comment by rudle** [comment]
I might be having a similar issue, but I can't see your screenshots. Can you re-host them somewhere?

**Comment by huxley-sparks** [comment]
Never mind, I got it. I had to uncomment term=builtin_ansi

> set t_Co=256

might have had helped as well.
