### ISSUE TITLE
matchparen highlighting difficult to read on dark

### ISSUE THREAD

**Issue by nathanlong** [altercation/vim-colors-solarized#37]
Using the dark scheme, highlights from the MatchParen plugin (`fg_red` and `bg_base01` on line 675) can be difficult to read. The highlighting looks fine on the light scheme.

I suggest using either `bg_base0` with the red, or using a different combination. I settled on `fg_back` and `bg_magenta`, but I'll leave it up to you.

I encountered this while using the [MatchTag plugin](https://github.com/gregsexton/MatchTag) and MacVim on OSX 10.6.8.

**Comment by AguirreIF** [comment]
I'm having the same issue, I just changed to `bg_base02` and it looks pretty well.

**Comment by ericbn** [comment]
Improved this using `bg_magenta` and `fg_base2` (on dark, or `fb_base02` on light background) on my fork: https://github.com/ericbn/vim-solarized
