### ISSUE TITLE
ToggleBG breaks colors

### ISSUE THREAD

**Issue by yuriihabrusiev** [altercation/vim-colors-solarized#42]
I try using solarized in term with **let g:solarized_termcolors=256** option. After using togglebg function, colors become broken. 
Images: before - http://imgur.com/A9ZBP after - http://imgur.com/PVjow

And, if i made manualy **:set background=light** and **:colorscheme solarized** everything ok!

**Comment by neoascetic** [comment]
Same for me.
@k3mm0tar did you find a solution for this?
