### ISSUE TITLE
matching brackets color with cursor on

### ISSUE THREAD

**Issue by enricostano** [altercation/vim-colors-solarized#47]
Hi,

I'm using Vim 7.3 and I've noticed that the matching brackets color is the same of the cursor color, so when you put the cursor on one of the two brackets you just can't see it.

In this image http://dl.dropbox.com/u/42986713/colors.png I'm with the cursor on the right bracket.

Would be better to leave the same bracket color as when the cursor isn't on it.

Thank you!

**Comment by foxbunny** [comment]
Cursor becomes red when placed over matching brackets for me.

**Comment by sigmavirus24** [comment]
I can definitely reproduce this, but when I `set bg=dark` I don't have the problem. This only happens in terminal vim though (using the Xresources provided by solarized). In gVim for example, this works fine in both dark and light backgrounds.

By the way I'm using plain old xterm. If that helps.

**Comment by catskul** [comment]
This still seems to be a problem as of vim 7.4 (Ubuntu 14.10).

**Comment by Doppp** [comment]
This might be a little off topic but does anyone else's Solarized colors look like this in Vim? Braces and `function` are not blue, for example.

![screen shot 2015-02-06 at 2 16 04 pm](https://cloud.githubusercontent.com/assets/627410/6075313/b85e39d4-ae0a-11e4-9b63-65a31083caf8.png)

According to the main [Solarized](http://ethanschoonover.com/solarized) site, it's supposed to look like: 

![](http://ethanschoonover.com/solarized/img/screen-javascript-dark.png)

I'm using iTerm2 with the color palette from [here](https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized). Am I missing something here?

**Comment by enricostano** [comment]
Maybe we can just close this one

**Comment by sigmavirus24** [comment]
@enricostano are you still having problems?

**Comment by enricostano** [comment]
@sigmavirus24 I switched to another color scheme, sorry
