### ISSUE TITLE
Light == Dark and vice versa

### ISSUE THREAD

**Issue by manolomartinez** [altercation/vim-colors-solarized#53]
This is something strange: I've noticed that both in `vim` and `mutt` the light background is served by the dark colourscheme and vice versa. Not so, for example, in `gvim`. This is no big deal, but it is slightly puzzling. Am I doing something wrong here?

**Comment by fedemp** [comment]
I have found the same issue but the good guys at vim-airline find the solution: https://github.com/bling/vim-airline/issues/240

@altercation I'm pinging you cause I think you should check the conversation over there. The Xresources for Solarized seems to doing the switch between dark and light in a wrong way.
