### ISSUE TITLE
Spell check colors

### ISSUE THREAD

**Issue by timofurrer** [altercation/vim-colors-solarized#84]
I recently started using vim's spell check feature. 
And I use solarized as well.

I see in the color file of solarized:

```
exe "hi! SpellBad"       .s:fmt_curl   .s:fg_none   .s:bg_none    .s:sp_red
exe "hi! SpellCap"       .s:fmt_curl   .s:fg_none   .s:bg_none    .s:sp_violet
exe "hi! SpellRare"      .s:fmt_curl   .s:fg_none   .s:bg_none    .s:sp_cyan
exe "hi! SpellLocal"     .s:fmt_curl   .s:fg_none   .s:bg_none    .s:sp_yellow
```

But my bad spelled words are actually not colored red. They are just underlined.
What do I have to do to become it highlighted red?

I run vim in console with 256 colors, with these settings:

```
let g:solarized_termtrans = 1

" set termcolors to 256 instead of std 16
let g:solarized_termcolors = 256

" set bold, underline and italic enable
let g:solarized_bold = 1
let g:solarized_underline = 1
let g:solarized_italic = 1
```

Thank guys :beers:

**Comment by ghost** [comment]
> But my bad spelled words are actually not colored red. They are just underlined.

@timofurrer, from what I see in the code, they are supposed to be underlined.
That is, your configuration is fine.
The `s:sp_red` makes the underline red, `s:fmt_curl` makes it curly, but these take effect only in gvim.
In console vim you get simple underlining, as you have already noticed.

If you want the traditional vim look, you can change `bg_none` to `bg_red`, `bg_cyan`, etc.
HTH

**Comment by timofurrer** [comment]
Okay, thank you!

**Comment by vext01** [comment]
+1 for making SpellBad more obvious in the terminal. Perhaps a different background colour?
