### ISSUE TITLE
Keep getting E488: Trailing characters: and other errors while loading vim

### ISSUE THREAD

**Issue by xinye1** [altercation/vim-colors-solarized#89]
Ubuntu 12.04
Gnome terminal 3.4.1.1

I manually moved all the folders in ~/.vim direcotry.

When loading vim it seems to give an error for almost every line of the color.vim file. Towards the end the errors are:

<pre><code>
E488: Trailing characters:   /div>/
line 1652:
E488: Trailing characters:     div id=
line 1653:
E488: Trailing characters:       span class=
line 1654:
E488: Trailing characters:       a href=
line 1655:
E492: Not an editor command:       Something went wrong with that request. Please try again.
line 1656:
E488: Trailing characters:     /div
line 1658:
E488: Trailing characters:   /body
line 1659:
"E488: Trailing characters: /html
</code></pre>

Can anyone help please?

Thanks
Xinye

**Comment by jimhavrilla** [comment]
happened to me too.
