### ISSUE TITLE
[suggestion] toplevel readme -- recommend creating a submodule, rather than cloning

### ISSUE THREAD

**Issue by benblazak** [altercation/vim-colors-solarized#90]
In the top-level readme, [here](https://github.com/altercation/vim-colors-solarized/blob/master/README.mkd#option-2-pathogen-installation-recommended), would it be better to say

``` bash
cd ~/.vim/bundle
git submodule add git://github.com/altercation/vim-colors-solarized.git
```

rather than

``` bash
cd ~/.vim/bundle
git clone git://github.com/altercation/vim-colors-solarized.git
```

?

I'm a bit hazy on the differences, but the former worked fine for me, with the added benefit that now [my "~/.vim/bundle/vim-colors-solarized" folder on github](https://github.com/benblazak/.vim/tree/master/bundle) nicely links to your repo.

**Comment by ysheng26** [comment]
The former won't work if others don't use git to track their `.vim` folder

`fatal: Not a git repository (or any of the parent directories): .git`

**Comment by benblazak** [comment]
I see.  Wasn't aware of that.  Thanks :)

Closed so as not to unduly bother anyone.  Listing three different ways to do the same thing might be a little excessive.  Those using git and wishing to create a proper submodule instead of simply cloning can probably find the answer themselves, as I did, without way too much trouble :) .
